# Generated by Django 4.2.6 on 2023-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_article_author_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
